# Numpy

In [30]:
sinav_1 = [100, 84, 76, 48, 36, 77, 90]
sinav_2 = [95, 78, 66, 57, 75, 89, 95]

ortalama = []
for i in range(len(sinav_1)):
    ortalama.append((sinav_1[i] + sinav_2[i]) / 2)

ortalama

[97.5, 81.0, 71.0, 52.5, 55.5, 83.0, 92.5]

In [10]:
sinav_1 = [100, 84, 76, 48, 36, 77, 90]
sinav_2 = [95, 78, 66, 57, 75, 89, 95]

(sinav_1 + sinav_2) / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [3]:
import numpy as np

liste = ["Adana", 1, "Adıyaman", 2, "Afyon", 3]
numpy_dizi = np.array(liste)

print(numpy_dizi)


['Adana' '1' 'Adıyaman' '2' 'Afyon' '3']


In [4]:
sinav_1 = [100, 84, 76, 48, 36, 77, 90]
sinav_2 = [95, 78, 66, 57, 75, 89, 95]
sinav_1_np = np.array(sinav_1)
sinav_2_np = np.array(sinav_2)

ortalama = (sinav_1_np + sinav_2_np) / 2

ortalama

array([97.5, 81. , 71. , 52.5, 55.5, 83. , 92.5])

In [5]:
sinav_1 + sinav_2

[100, 84, 76, 48, 36, 77, 90, 95, 78, 66, 57, 75, 89, 95]

In [6]:
sinav_1_np + sinav_2_np

array([195, 162, 142, 105, 111, 166, 185])

In [7]:
sinav_1_np[3]

48

In [8]:
ortalama < 70

array([False, False, False,  True,  True, False, False])

In [9]:
ortalama[ortalama < 70]

array([52.5, 55.5])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [12]:
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [13]:
np.linspace(-2,2,100)

array([-2.        , -1.95959596, -1.91919192, -1.87878788, -1.83838384,
       -1.7979798 , -1.75757576, -1.71717172, -1.67676768, -1.63636364,
       -1.5959596 , -1.55555556, -1.51515152, -1.47474747, -1.43434343,
       -1.39393939, -1.35353535, -1.31313131, -1.27272727, -1.23232323,
       -1.19191919, -1.15151515, -1.11111111, -1.07070707, -1.03030303,
       -0.98989899, -0.94949495, -0.90909091, -0.86868687, -0.82828283,
       -0.78787879, -0.74747475, -0.70707071, -0.66666667, -0.62626263,
       -0.58585859, -0.54545455, -0.50505051, -0.46464646, -0.42424242,
       -0.38383838, -0.34343434, -0.3030303 , -0.26262626, -0.22222222,
       -0.18181818, -0.14141414, -0.1010101 , -0.06060606, -0.02020202,
        0.02020202,  0.06060606,  0.1010101 ,  0.14141414,  0.18181818,
        0.22222222,  0.26262626,  0.3030303 ,  0.34343434,  0.38383838,
        0.42424242,  0.46464646,  0.50505051,  0.54545455,  0.58585859,
        0.62626263,  0.66666667,  0.70707071,  0.74747475,  0.78

In [14]:
hisse = np.array([3.4, 3.6, 3.9, 4.2, 4.0, 3.8])
type(hisse)

numpy.ndarray

In [15]:
hisse_fiyat = np.array([[3.57, 4.42, 5.25, 12.50, 29.30],
                        [3.43, 4.69, 5.00, 11.00, 32.12],
                        [3.15, 4.35, 4.95, 10.50, 29.00]])
print(hisse_fiyat)

[[ 3.57  4.42  5.25 12.5  29.3 ]
 [ 3.43  4.69  5.   11.   32.12]
 [ 3.15  4.35  4.95 10.5  29.  ]]


In [16]:
dizi = np.arange(20)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
dizi[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
dizi[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
dizi[5:10]

array([5, 6, 7, 8, 9])

In [20]:
dizi[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
matris = dizi.reshape(4,5)
matris

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
matris[2:3,3:4]

array([[13]])

In [26]:
matris[2,3]

13

In [27]:
matris[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
hisse_fiyat = np.array([[3.57, 4.42, 5.25, 12.50, 29.30],
                        [3.43, 4.69, 5.00, 11.00, 32.12],
                        [3.15, 4.35, 4.95, 10.50, 29.00]])

hisse_fiyat.shape

(3, 5)

In [32]:
dizi = np.array([[[2, 3, 4, 5],
                  [6, 7, 8, 9],
                [10,11,12,13]],
                [[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]]])
dizi.shape

(2, 3, 4)

In [33]:
dizi

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [34]:
dizi.T

array([[[ 2,  1],
        [ 6,  5],
        [10,  9]],

       [[ 3,  2],
        [ 7,  6],
        [11, 10]],

       [[ 4,  3],
        [ 8,  7],
        [12, 11]],

       [[ 5,  4],
        [ 9,  8],
        [13, 12]]])

In [35]:
dizi

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [36]:
dizi.shape

(2, 3, 4)

In [37]:
dizi.sum(0)

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [38]:
dizi.sum(1)

array([[18, 21, 24, 27],
       [15, 18, 21, 24]])

In [39]:
dizi.sum(2)

array([[14, 30, 46],
       [10, 26, 42]])

In [40]:
hisse_fiyat

array([[ 3.57,  4.42,  5.25, 12.5 , 29.3 ],
       [ 3.43,  4.69,  5.  , 11.  , 32.12],
       [ 3.15,  4.35,  4.95, 10.5 , 29.  ]])

In [41]:
hisse_fiyat.shape

(3, 5)

In [42]:
hisse_fiyat.cumsum(0)

array([[ 3.57,  4.42,  5.25, 12.5 , 29.3 ],
       [ 7.  ,  9.11, 10.25, 23.5 , 61.42],
       [10.15, 13.46, 15.2 , 34.  , 90.42]])

In [43]:
hisse_fiyat.cumsum(1)

array([[ 3.57,  7.99, 13.24, 25.74, 55.04],
       [ 3.43,  8.12, 13.12, 24.12, 56.24],
       [ 3.15,  7.5 , 12.45, 22.95, 51.95]])

In [44]:
dizi = np.array([21,54,-45,56,234,0,1])

In [45]:
dizi.max()

234

In [46]:
dizi.argmax()

4

In [47]:
dizi.min()

-45

In [48]:
dizi.argmin()

2

In [49]:
dizi.ptp()

279

In [50]:
dizi.clip(1,100)

array([ 21,  54,   1,  56, 100,   1,   1])

In [53]:
dizi = np.array([1.23,-5.2354,5.998,4.56])
dizi.round(1)

array([ 1.2, -5.2,  6. ,  4.6])

In [54]:
hisse_fiyat

array([[ 3.57,  4.42,  5.25, 12.5 , 29.3 ],
       [ 3.43,  4.69,  5.  , 11.  , 32.12],
       [ 3.15,  4.35,  4.95, 10.5 , 29.  ]])

In [55]:
hisse_fiyat.mean(0)

array([ 3.38333333,  4.48666667,  5.06666667, 11.33333333, 30.14      ])

In [56]:
hisse_fiyat.mean(1)

array([11.008, 11.248, 10.39 ])

In [57]:
hisse_fiyat.var(1)

array([ 93.740696, 115.773576,  92.9674  ])

In [58]:
hisse_fiyat.std(1)

array([ 9.6819779 , 10.75981301,  9.64196038])

In [59]:
hisse_fiyat

array([[ 3.57,  4.42,  5.25, 12.5 , 29.3 ],
       [ 3.43,  4.69,  5.  , 11.  , 32.12],
       [ 3.15,  4.35,  4.95, 10.5 , 29.  ]])

In [61]:
hisse_fiyat.sort(0)
hisse_fiyat

array([[ 3.15,  4.35,  4.95, 10.5 , 29.  ],
       [ 3.43,  4.42,  5.  , 11.  , 29.3 ],
       [ 3.57,  4.69,  5.25, 12.5 , 32.12]])

In [62]:
hisse_fiyat.sort(1)
hisse_fiyat

array([[ 3.15,  4.35,  4.95, 10.5 , 29.  ],
       [ 3.43,  4.42,  5.  , 11.  , 29.3 ],
       [ 3.57,  4.69,  5.25, 12.5 , 32.12]])

In [64]:
a = np.array([  [3, 4, 7, 4],
                [2, 9, 4, 2],
                [1, 5, 8, 3]])

b = np.array([  [4, 2, 8, 9],
                [6, 3, 6, 1],
                [3, 2, 4, 2]])

In [65]:
np.mean(a[:,1])

6.0

In [66]:
np.std(b[2,:])

0.82915619758885

In [67]:
for i in a:
    print(i)

[3 4 7 4]
[2 9 4 2]
[1 5 8 3]


In [68]:
for i in np.nditer(a):
    print(i)

3
4
7
4
2
9
4
2
1
5
8
3
